
/*INSERT INTO SUBREDDIT ( CREATED_DATE, DESCRIPTION, NAME, USER_ID) VALUES ( CURRENT_DATE(), 'Nottingham News DESC 1 ', 'Nottingham topic 1 ' ,'1');
INSERT INTO SUBREDDIT ( CREATED_DATE, DESCRIPTION, NAME, USER_ID) VALUES ( CURRENT_DATE(), 'Nottingham News DESC 2 ' , 'Nottingham topic 2' ,'1');
INSERT INTO SUBREDDIT ( CREATED_DATE, DESCRIPTION, NAME, USER_ID) VALUES ( CURRENT_DATE(), 'Nottingham News DESC 3', 'Nottingham topic 3 ' ,'1');
INSERT INTO SUBREDDIT (CREATED_DATE, DESCRIPTION, NAME, USER_ID) VALUES ( CURRENT_DATE(), 'Nottingham News DESC 4 ', 'Nottingham topic 4 ' ,'1');

*/
